from sqlalchemy import (
    Column, Integer, String, Text, Boolean,
    Numeric, Date, DateTime, ForeignKey, func, Computed
)
from sqlalchemy.orm import relationship
from database import Base

class AdvancePayment(Base):
    __tablename__ = "advance_payments"
    adv_id          = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False, index=True)
    voucher_no      = Column(String(30), unique=True, nullable=False)
    voucher_date    = Column(Date, nullable=False)
    gl_party_id     = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False, index=True)
    party_name      = Column(String(200), nullable=False)
    party_type      = Column(String(10), nullable=False, default='Supplier')
    gl_cashbank_id  = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False)
    cashbank_name   = Column(String(200))
    amount          = Column(Numeric(12,2), nullable=False)
    adjusted_amount = Column(Numeric(12,2), nullable=False, default=0)
    balance         = Column(Numeric(12,2), Computed("amount - adjusted_amount"))
    doc_no          = Column(String(50))
    doc_date        = Column(Date)
    narration       = Column(Text)
    status          = Column(String(20), nullable=False, default='Open', index=True)
    created_by      = Column(Integer, ForeignKey("users.user_id"))
    created_at      = Column(DateTime, default=func.now(), nullable=False)

class BankArrival(Base):
    __tablename__ = "bank_arrivals"
    arrival_id      = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False, index=True)
    voucher_no      = Column(String(30), unique=True, nullable=False)
    voucher_date    = Column(Date, nullable=False)
    gl_party_id     = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False, index=True)
    party_name      = Column(String(200), nullable=False)
    gl_bank_id      = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False)
    bank_name       = Column(String(200))
    amount          = Column(Numeric(12,2), nullable=False)
    entered_amount  = Column(Numeric(12,2), nullable=False, default=0)
    balance         = Column(Numeric(12,2), Computed("amount - entered_amount"))
    ref_doc_no      = Column(String(50))
    ref_doc_date    = Column(Date)
    narration       = Column(Text)
    status          = Column(String(20), nullable=False, default='Open', index=True)
    created_by      = Column(Integer, ForeignKey("users.user_id"))
    created_at      = Column(DateTime, default=func.now(), nullable=False)

class GLPosting(Base):
    __tablename__ = "gl_postings"
    posting_id      = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False, index=True)
    posting_date    = Column(Date, nullable=False, index=True)
    gl_id           = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False, index=True)
    voucher_type    = Column(String(20), nullable=False)
    voucher_no      = Column(String(30), nullable=False)
    voucher_ref_id  = Column(Integer, nullable=False)
    dr_amount       = Column(Numeric(14,2), nullable=False, default=0)
    cr_amount       = Column(Numeric(14,2), nullable=False, default=0)
    narration       = Column(Text)
    created_at      = Column(DateTime, default=func.now(), nullable=False)

class ReceiptVoucher(Base):
    __tablename__ = "receipt_vouchers"
    receipt_id      = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False)
    receipt_no      = Column(String(30), unique=True, nullable=False)
    receipt_date    = Column(Date, nullable=False)
    owner_id        = Column(Integer, ForeignKey("pet_owners.owner_id"), nullable=False)
    gl_party_id     = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False)
    gl_cashbank_id  = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False)
    total_amount    = Column(Numeric(12,2), nullable=False)
    payment_type    = Column(String(20), nullable=False, default='Cash')
    ref_no          = Column(String(50))
    ref_date        = Column(Date)
    narration       = Column(Text)
    status          = Column(String(20), nullable=False, default='Posted')
    created_by      = Column(Integer, ForeignKey("users.user_id"))
    created_at      = Column(DateTime, default=func.now(), nullable=False)

    details         = relationship("ReceiptVoucherDetail", back_populates="receipt", cascade="all, delete-orphan")

class ReceiptVoucherDetail(Base):
    __tablename__ = "receipt_voucher_details"
    detail_id       = Column(Integer, primary_key=True)
    receipt_id      = Column(Integer, ForeignKey("receipt_vouchers.receipt_id", ondelete="CASCADE"), nullable=False, index=True)
    line_no         = Column(Integer, nullable=False)
    vou_type        = Column(String(10), nullable=False)
    bill_id         = Column(Integer, ForeignKey("sales_bills.bill_id"), index=True)
    bill_no         = Column(String(50))
    bill_date       = Column(Date)
    bill_amount     = Column(Numeric(12,2))
    prev_received   = Column(Numeric(12,2), default=0)
    balance_amount  = Column(Numeric(12,2))
    amount_received = Column(Numeric(12,2), nullable=False)
    arrival_id      = Column(Integer, ForeignKey("bank_arrivals.arrival_id"))

    receipt         = relationship("ReceiptVoucher", back_populates="details")

class PaymentVoucher(Base):
    __tablename__ = "payment_vouchers"
    payment_id      = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False, index=True)
    voucher_no      = Column(String(30), unique=True, nullable=False)
    voucher_date    = Column(Date, nullable=False)
    gl_party_id     = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False, index=True)
    party_name      = Column(String(200), nullable=False)
    gl_cashbank_id  = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False)
    cashbank_name   = Column(String(200))
    total_amount    = Column(Numeric(12,2), nullable=False)
    payment_type    = Column(String(20), nullable=False, default='Cash')
    ref_no          = Column(String(50))
    ref_date        = Column(Date)
    narration       = Column(Text)
    status          = Column(String(20), nullable=False, default='Posted')
    created_by      = Column(Integer, ForeignKey("users.user_id"))
    created_at      = Column(DateTime, default=func.now(), nullable=False)

    details         = relationship("PaymentVoucherDetail", back_populates="payment", cascade="all, delete-orphan")

class PaymentVoucherDetail(Base):
    __tablename__ = "payment_voucher_details"
    detail_id       = Column(Integer, primary_key=True)
    payment_id      = Column(Integer, ForeignKey("payment_vouchers.payment_id", ondelete="CASCADE"), nullable=False, index=True)
    line_no         = Column(Integer, nullable=False)
    vou_type        = Column(String(10), nullable=False)
    bill_id         = Column(Integer, ForeignKey("purchase_bills.bill_id"), index=True)
    bill_no         = Column(String(50))
    bill_date       = Column(Date)
    bill_amount     = Column(Numeric(12,2))
    prev_paid       = Column(Numeric(12,2), default=0)
    balance_amount  = Column(Numeric(12,2))
    amount_paid     = Column(Numeric(12,2), nullable=False)
    adv_id          = Column(Integer, ForeignKey("advance_payments.adv_id"))

    payment         = relationship("PaymentVoucher", back_populates="details")

class JournalVoucher(Base):
    __tablename__ = "journal_vouchers"
    journal_id      = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False, index=True)
    voucher_no      = Column(String(30), unique=True, nullable=False)
    voucher_date    = Column(Date, nullable=False)
    bill_ref_no     = Column(String(50))
    narration       = Column(Text, nullable=False)
    total_cr        = Column(Numeric(14,2), nullable=False, default=0)
    total_dr        = Column(Numeric(14,2), nullable=False, default=0)
    status          = Column(String(20), nullable=False, default='Posted')
    created_by      = Column(Integer, ForeignKey("users.user_id"))
    created_at      = Column(DateTime, default=func.now(), nullable=False)

    lines           = relationship("JournalLine", back_populates="journal", cascade="all, delete-orphan")

class JournalLine(Base):
    __tablename__ = "journal_lines"
    line_id         = Column(Integer, primary_key=True)
    journal_id      = Column(Integer, ForeignKey("journal_vouchers.journal_id", ondelete="CASCADE"), nullable=False, index=True)
    line_no         = Column(Integer, nullable=False)
    gl_cr_id        = Column(Integer, ForeignKey("gl_master.gl_id"), index=True)
    cr_account_name = Column(String(200))
    gl_dr_id        = Column(Integer, ForeignKey("gl_master.gl_id"), index=True)
    dr_account_name = Column(String(200))
    cr_amount       = Column(Numeric(12,2), nullable=False, default=0)
    dr_amount       = Column(Numeric(12,2), nullable=False, default=0)

    journal         = relationship("JournalVoucher", back_populates="lines")

class CreditNote(Base):
    __tablename__ = "credit_notes"
    cn_id           = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False, index=True)
    voucher_no      = Column(String(30), unique=True, nullable=False)
    voucher_date    = Column(Date, nullable=False)
    ref_bill_id     = Column(Integer, ForeignKey("sales_bills.bill_id"))
    ref_bill_no     = Column(String(50))
    ref_bill_date   = Column(Date)
    gl_party_id     = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False, index=True)
    party_name      = Column(String(200), nullable=False)
    gl_credit_id    = Column(Integer, ForeignKey("gl_master.gl_id"))
    credit_desc     = Column(String(200))
    address1        = Column(Text)
    address2        = Column(Text)
    city            = Column(String(100))
    state_code      = Column(String(10))
    gstin           = Column(String(20))
    is_interstate   = Column(Boolean, nullable=False, default=False)
    total_qty       = Column(Numeric(10,3), default=0)
    gross_amount    = Column(Numeric(12,2), default=0)
    discount_pct    = Column(Numeric(5,2), default=0)
    discount_amt    = Column(Numeric(10,2), default=0)
    taxable_amount  = Column(Numeric(12,2), default=0)
    cgst_rate       = Column(Numeric(5,2), default=0)
    cgst_amount     = Column(Numeric(10,2), default=0)
    sgst_rate       = Column(Numeric(5,2), default=0)
    sgst_amount     = Column(Numeric(10,2), default=0)
    igst_rate       = Column(Numeric(5,2), default=0)
    igst_amount     = Column(Numeric(10,2), default=0)
    round_off       = Column(Numeric(6,2), default=0)
    net_amount      = Column(Numeric(12,2), default=0)
    narration       = Column(Text)
    status          = Column(String(20), nullable=False, default='Confirmed')
    created_by      = Column(Integer, ForeignKey("users.user_id"))
    created_at      = Column(DateTime, default=func.now(), nullable=False)

    items           = relationship("CreditNoteItem", back_populates="credit_note", cascade="all, delete-orphan")

class CreditNoteItem(Base):
    __tablename__ = "credit_note_items"
    item_id         = Column(Integer, primary_key=True)
    cn_id           = Column(Integer, ForeignKey("credit_notes.cn_id", ondelete="CASCADE"), nullable=False, index=True)
    line_no         = Column(Integer, nullable=False)
    medicine_id     = Column(Integer, ForeignKey("medicines.medicine_id"))
    procedure_id    = Column(Integer, ForeignKey("procedures.procedure_id"))
    item_code       = Column(String(50))
    item_name       = Column(String(200), nullable=False)
    hsn_code        = Column(String(20))
    unit            = Column(String(20))
    quantity        = Column(Numeric(10,3))
    rate            = Column(Numeric(10,2))
    discount_pct    = Column(Numeric(5,2), default=0)
    discount_amt    = Column(Numeric(10,2), default=0)
    taxable_amount  = Column(Numeric(10,2))
    gst_pct         = Column(Numeric(5,2))
    cgst_amount     = Column(Numeric(10,2))
    sgst_amount     = Column(Numeric(10,2))
    igst_amount     = Column(Numeric(10,2))
    line_total      = Column(Numeric(10,2))

    credit_note     = relationship("CreditNote", back_populates="items")

class DebitNote(Base):
    __tablename__ = "debit_notes"
    dn_id           = Column(Integer, primary_key=True)
    fy_code         = Column(String(10), ForeignKey("financial_years.fy_code"), nullable=False, index=True)
    voucher_no      = Column(String(30), unique=True, nullable=False)
    voucher_date    = Column(Date, nullable=False)
    ref_bill_id     = Column(Integer, ForeignKey("purchase_bills.bill_id"))
    ref_bill_no     = Column(String(50))
    ref_bill_date   = Column(Date)
    gl_party_id     = Column(Integer, ForeignKey("gl_master.gl_id"), nullable=False, index=True)
    party_name      = Column(String(200), nullable=False)
    gl_debit_id     = Column(Integer, ForeignKey("gl_master.gl_id"))
    debit_desc      = Column(String(200))
    address1        = Column(Text)
    address2        = Column(Text)
    city            = Column(String(100))
    supplier_id     = Column(Integer, ForeignKey("suppliers.supplier_id"))
    state_code      = Column(String(10))
    gstin           = Column(String(20))
    is_interstate   = Column(Boolean, nullable=False, default=False)
    total_qty       = Column(Numeric(10,3), default=0)
    gross_amount    = Column(Numeric(12,2), default=0)
    discount_pct    = Column(Numeric(5,2), default=0)
    discount_amt    = Column(Numeric(10,2), default=0)
    taxable_amount  = Column(Numeric(12,2), default=0)
    cgst_rate       = Column(Numeric(5,2), default=0)
    cgst_amount     = Column(Numeric(10,2), default=0)
    sgst_rate       = Column(Numeric(5,2), default=0)
    sgst_amount     = Column(Numeric(10,2), default=0)
    igst_rate       = Column(Numeric(5,2), default=0)
    igst_amount     = Column(Numeric(10,2), default=0)
    round_off       = Column(Numeric(6,2), default=0)
    net_amount      = Column(Numeric(12,2), default=0)
    narration       = Column(Text)
    status          = Column(String(20), nullable=False, default='Confirmed')
    created_by      = Column(Integer, ForeignKey("users.user_id"))
    created_at      = Column(DateTime, default=func.now(), nullable=False)

    items           = relationship("DebitNoteItem", back_populates="debit_note", cascade="all, delete-orphan")

class DebitNoteItem(Base):
    __tablename__ = "debit_note_items"
    item_id         = Column(Integer, primary_key=True)
    dn_id           = Column(Integer, ForeignKey("debit_notes.dn_id", ondelete="CASCADE"), nullable=False, index=True)
    line_no         = Column(Integer, nullable=False)
    medicine_id     = Column(Integer, ForeignKey("medicines.medicine_id"))
    item_code       = Column(String(50))
    item_name       = Column(String(200), nullable=False)
    hsn_code        = Column(String(20))
    unit            = Column(String(20))
    quantity        = Column(Numeric(10,3))
    rate            = Column(Numeric(10,2))
    discount_pct    = Column(Numeric(5,2), default=0)
    discount_amt    = Column(Numeric(10,2), default=0)
    taxable_amount  = Column(Numeric(10,2))
    gst_pct         = Column(Numeric(5,2))
    cgst_amount     = Column(Numeric(10,2))
    sgst_amount     = Column(Numeric(10,2))
    igst_amount     = Column(Numeric(10,2))
    line_total      = Column(Numeric(10,2))

    debit_note      = relationship("DebitNote", back_populates="items")
